apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- configmap.yaml
- pvc.yaml
- service.yaml
- ingress.yaml
namePrefix: prod-
images:
- name: ceappacr.azurecr.io/
  newTag: "202411191543"
- name: ceappacr.azurecr.io/app-82265825
  newTag: "202411191618"
