configMapGenerator:
- files:
  - application.yml
  name: app-82265825-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: ceappacr.azurecr.io/app-82265825
  newTag: "202411200033"
- name: ceappacr.azurecr.io/troubleshooting
  newTag: latest
